"""Version-gated heal: recover from the v<=0.12.2 branch-ref cache
drift bug for users upgrading to a fixed APM release.

Lockfiles generated by APM <= 0.12.2 may contain a phantom
``resolved_commit`` (the remote HEAD at the time of the buggy install)
while the on-disk content reflects an older commit. The content-hash
fallback in ``_resolve_download_strategy`` happily declares
``lockfile_match=True`` because both lockfile content_hash and disk
content reflect the OLD bytes, so the lie persists indefinitely until
upstream advances again.

When we detect this combination (buggy lockfile generator + branch ref
+ content-hash-only match), force a one-time re-download. The
subsequent install records the current apm_version, so the trigger
does not re-fire on releases past 0.12.2.

Shares ``exclusive_group="branch_drift"`` with
:class:`BranchRefDriftHeal` so the two never fire on the same dep --
the always-on drift heal handles the case where the remote has
advanced; this heal handles the case where the remote has NOT advanced
but the lockfile is still corrupted from the buggy era.
"""

from __future__ import annotations

from typing import Any

from .base import HealContext, HealMessageLevel

# Lockfiles produced by these APM versions may contain phantom
# ``resolved_commit`` values for branch-ref deps (3-way drift bug).
# When such a lockfile is detected, this heal forces a one-time
# re-download of branch-ref deps that match via content-hash fallback
# only. See PR #1158.
_BUGGY_BRANCH_REF_DRIFT_VERSIONS = frozenset(
    {
        "0.10.0",
        "0.10.1",
        "0.10.2",
        "0.11.0",
        "0.11.1",
        "0.11.2",
        "0.12.0",
        "0.12.1",
        "0.12.2",
    }
)


def _is_buggy_lockfile_apm_version(existing_lockfile: Any) -> bool:
    """Return True when *existing_lockfile* was generated by an APM
    version known to suffer from the branch-ref cache-drift bug.

    Conservative default (False when version is missing): the self-heal
    path is opt-in -- only trigger for lockfiles we can positively
    identify as affected.
    """
    if existing_lockfile is None:
        return False
    recorded = getattr(existing_lockfile, "apm_version", None)
    if not recorded:
        return False
    return recorded in _BUGGY_BRANCH_REF_DRIFT_VERSIONS


class BuggyLockfileRecoveryHeal:
    name = "buggy_lockfile_recovery"
    order = 20
    exclusive_group = "branch_drift"

    def applies(self, hctx: HealContext) -> bool:
        from apm_cli.models.apm_package import GitReferenceType

        return (
            hctx.lockfile_match
            and hctx.lockfile_match_via_content_hash_only
            and not hctx.update_refs
            and hctx.resolved_ref is not None
            and hctx.resolved_ref.ref_type == GitReferenceType.BRANCH
            and _is_buggy_lockfile_apm_version(hctx.existing_lockfile)
        )

    def execute(self, hctx: HealContext) -> None:
        hctx.lockfile_match = False
        hctx.ref_changed = True
        # In the corrupted state, lockfile.content_hash records OLD
        # bytes while disk content is also OLD. The forced re-download
        # will produce NEW bytes whose hash differs from the OLD
        # lockfile hash. Tell the FreshDependencySource that this
        # change is LEGITIMATE -- otherwise the supply-chain hard-block
        # would abort before we can repair the lockfile.
        hctx.add_bypass_key(hctx.package_key)
        hctx.emit(
            HealMessageLevel.WARN,
            f"Recovering {hctx.package_key} from "
            "branch-ref cache drift in lockfile generated by APM <= 0.12.2 "
            "-- forcing re-download to restore consistency. "
            "Upgrade APM (>= 0.13.0) to prevent recurrence.",
        )
